### ISSUE TITLE
An alias would be fine

### ISSUE THREAD

**Issue by fernandosouza** [wedeploy/electric-cli#2]
I think `electric` is a long word to type into the terminal. We can often forget a letter and it will be frustrating to retype it again. Could we create an `alias` like `el`, `elec`?

**Comment by robframpton** [comment]
Yeah I like this idea, it should be as simple as adding another property to [bin](https://github.com/wedeploy/electric-cli/blob/master/package.json#L11). It will just point to the same file as `electric`.

I like `elec`, @zenorocha what do you think?

**Comment by zenorocha** [comment]
I like `el`, two letters shorter.
