### ISSUE TITLE
Suggestion - Be able to see version of package

### ISSUE THREAD

**Issue by NolanChan** [wedeploy/electric-cli#9]
When I query electric with `help` I currently see:

```
nolanchan ~ $ electric --help
Commands:
  build   Builds site and places files in dist.
  deploy  Builds site and and deploys dist files to git branch.
  init    Initializes a new electric project.
  run     Builds site, and starts up watch task along with development server.
  server  Starts development server for local testing.
  watch   Watches for changes to src files.

Options:
  --help  Show help
```

However, **there is no option to see the current version** of electric-cli. Having something like npm's version command would be great

```
nolanchan ~ $ npm -v
3.10.8
```

Update:
There also seems to be some mismatch between the [version name on npmjs.com](https://www.npmjs.com/package/electric-cli) and the actual version pulled down.  npmjs.com claims that 2.0.0-alpha.0 is the most up to date version, but the version that was downloaded today was 2.0.0-alpha.3

**Comment by zenorocha** [comment]
This problem you mentioned is related to how npm handles alpha tags, we'll not have that anymore once we start publishing stable versions.
